import type { NodeKind, NodeSpec } from "./types";

const OUT_NUM = { id: "out", label: "out", type: "number" as const };
const IN_NUM = { id: "input", label: "in", type: "number" as const };

export const NODE_SPECS: Record<NodeKind, NodeSpec> = {
  tracker_signal: {
    kind: "tracker_signal",
    label: "Tracker Signal",
    category: "source",
    inputs: [],
    outputs: [OUT_NUM],
    defaultConfig: { signal_path: "mp.hand.left.landmark.index_tip.x" },
    description: "Reads a named value from the live SignalBus.",
  },
  constant: {
    kind: "constant",
    label: "Constant",
    category: "source",
    inputs: [],
    outputs: [OUT_NUM],
    defaultConfig: { value: 0 },
    description: "A fixed numeric value.",
  },
  map_range: {
    kind: "map_range",
    label: "Map Range",
    category: "transform",
    inputs: [IN_NUM],
    outputs: [OUT_NUM],
    defaultConfig: {
      in_min: 0,
      in_max: 1,
      out_min: 0,
      out_max: 1,
      clamp: true,
      invert: false,
    },
    description: "Rescales a value from one range to another.",
  },
  clamp: {
    kind: "clamp",
    label: "Clamp",
    category: "transform",
    inputs: [IN_NUM],
    outputs: [OUT_NUM],
    defaultConfig: { min: 0, max: 1 },
    description: "Clamps a value to [min, max].",
  },
  invert: {
    kind: "invert",
    label: "Invert",
    category: "transform",
    inputs: [IN_NUM],
    outputs: [OUT_NUM],
    defaultConfig: { min: 0, max: 1 },
    description: "Mirrors a value around the midpoint of [min, max].",
  },
  add: {
    kind: "add",
    label: "Add",
    category: "transform",
    inputs: [
      { id: "a", label: "a", type: "number" },
      { id: "b", label: "b", type: "number" },
    ],
    outputs: [OUT_NUM],
    defaultConfig: {},
    description: "Outputs a + b.",
  },
  multiply: {
    kind: "multiply",
    label: "Multiply",
    category: "transform",
    inputs: [
      { id: "a", label: "a", type: "number" },
      { id: "b", label: "b", type: "number" },
    ],
    outputs: [OUT_NUM],
    defaultConfig: {},
    description: "Outputs a * b.",
  },
  smooth: {
    kind: "smooth",
    label: "Smooth",
    category: "transform",
    inputs: [IN_NUM],
    outputs: [OUT_NUM],
    defaultConfig: { alpha: 0.2 },
    description: "One-pole low-pass smoothing, alpha in [0, 1].",
  },
  deadzone: {
    kind: "deadzone",
    label: "Deadzone",
    category: "transform",
    inputs: [IN_NUM],
    outputs: [OUT_NUM],
    defaultConfig: { center: 0.5, radius: 0.05 },
    description: "Snaps values near `center` to `center`.",
  },
  threshold: {
    kind: "threshold",
    label: "Threshold",
    category: "transform",
    inputs: [IN_NUM],
    outputs: [{ id: "out", label: "out", type: "bool" }],
    defaultConfig: { threshold: 0.5 },
    description: "True when input >= threshold.",
  },
  debug_meter: {
    kind: "debug_meter",
    label: "Debug Meter",
    category: "debug",
    inputs: [IN_NUM],
    outputs: [OUT_NUM],
    defaultConfig: {},
    description: "Passes input through; shows live value in the UI.",
  },
  osc_out: {
    kind: "osc_out",
    label: "OSC Out",
    category: "output",
    inputs: [IN_NUM],
    outputs: [],
    defaultConfig: {
      host: "127.0.0.1",
      port: 9000,
      address: "/signalgraph/out",
      payload_type: "float",
      enabled: true,
    },
    description: "Sends outgoing OSC packets.",
  },
};

export const NODE_ORDER: NodeKind[] = [
  "tracker_signal",
  "constant",
  "map_range",
  "clamp",
  "invert",
  "add",
  "multiply",
  "smooth",
  "deadzone",
  "threshold",
  "debug_meter",
  "osc_out",
];
